name: 'Setup OpenHarmony SDK'
description: 'Download an install the OpenHarmony SDK'
inputs:
  version:
    description: 'OpenHarmony SDK release version'
    required: false
    default: '4.1'
  cache:
    description: "Whether to cache the SDK or not"
    required: false
    default: 'true'
  components:
    description: "Semicolon separated list of SDK components that should be made available"
    required: false
    default: 'native'
  fixup-path:
    description: "Whether to fixup the output paths so that the components appear under api level directory"
    required: false
    default: false
  mirror:
    description: "Prefer downloading from Github Releases SDK mirror"
    required: false
    default: 'true'
outputs:
  sdk-path:
    description: "Root directory of the OpenHarmony SDK installation"
    value: ${{ steps.install_ohos_sdk.outputs.sdk-path }}
  ohos_sdk_native:
    description: "The `native` directory inside the OpenHarmony SDK"
    value: ${{ steps.install_ohos_sdk.outputs.ohos_sdk_native }}
  sdk-version:
    description: "Specific version of the OpenHarmony SDK (e.g. 4.1.7.5)"
    value: ${{ steps.install_ohos_sdk.outputs.sdk-version }}
  api-version:
    description: "OpenHarmony API version of the SDK"
    value: ${{ steps.install_ohos_sdk.outputs.api-version }}
  ohos-base-sdk-home:
    description: "Path to the OpenHarmony SDK for the host platform"
    value: ${{ steps.install_ohos_sdk.outputs.ohos-base-sdk-home }}
runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: echo "Cache ${{ inputs.cache }}, version ${{ inputs.version }}, components ${{ inputs.components }}, fixup ${{ inputs.fixup-path }}"
    - name: Cache SDK
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/ohos-sdk
        key: "${{ runner.os }}-ohos-sdk-${{ inputs.version }}-${{ inputs.components }}-${{ inputs.fixup-path }}"
      if: ${{ inputs.cache == 'true' }}
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Download and install OpenHarmony SDK
      id: install_ohos_sdk
      run: install_ohos_sdk.sh
      shell: bash
      if: ${{ inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true' }}
      env:
        INPUT_VERSION: "${{ inputs.version }}"
        INPUT_COMPONENTS: "${{ inputs.components }}"
        INPUT_FIXUP_PATH: ${{ inputs.fixup-path }}
        INPUT_MIRROR: "${{ inputs.mirror }}"
        GH_TOKEN: "${{ github.token }}"
